/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.alee.laf.WebLookAndFeel;
import controller.TestWindowController;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Augustop
 */
public class TestWindow extends javax.swing.JFrame {
    TestWindowController controller;
    
    
    /**
     * Creates new form TestWindow
     */
    public TestWindow() {
        initComponents();
    }
    
    public TestWindow(TestWindowController ctr) {
        try {
            javax.swing.UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.controller = ctr;
        this.inputTamanho.requestFocus();
    }
    
    private void setButtonColor(com.alee.laf.button.WebButton b, Color fore, Color selFor, Color top, Color topSel, Color bot, Color botSel){
        b.setForeground (fore);
        b.setSelectedForeground (selFor);
        b.setTopBgColor (top);
        b.setTopSelectedBgColor (topSel);
        b.setBottomBgColor (bot);
        b.setBottomSelectedBgColor (botSel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoRetornar = new javax.swing.JButton();
        labelTamanho = new javax.swing.JLabel();
        inputTamanho = new javax.swing.JTextField();
        labelRepeticoes = new javax.swing.JLabel();
        inputRepeticoes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputRotinas = new javax.swing.JTextArea();
        labelRotina = new javax.swing.JLabel();
        botaoIniciarRotina = new javax.swing.JButton();
        botaoIncluirTeste = new javax.swing.JButton();
        botaoLimparRotina = new javax.swing.JButton();
        botaoLimparDados = new javax.swing.JButton();
        labelMensagem = new javax.swing.JLabel();
        botaoNumLog = new javax.swing.JButton();
        labelMedia = new javax.swing.JLabel();
        inputMedia = new javax.swing.JTextField();
        inputDesvio = new javax.swing.JTextField();
        labelDesvio = new javax.swing.JLabel();
        labelDistRepeticoes = new javax.swing.JLabel();
        inputDistRepeticoes = new javax.swing.JTextField();
        labelExtra = new javax.swing.JLabel();
        inputExtra = new javax.swing.JTextField();
        botaoNumExp = new javax.swing.JButton();
        labelExtraExp = new javax.swing.JLabel();
        inputExtraExp = new javax.swing.JTextField();
        inputLambda = new javax.swing.JTextField();
        labelLambda = new javax.swing.JLabel();
        labelDistRepeExp = new javax.swing.JLabel();
        inputDistRepExp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo de Testes");
        setResizable(false);

        botaoRetornar.setText("Retornar ao Tabuleiro");
        botaoRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRetornarActionPerformed(evt);
            }
        });

        labelTamanho.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelTamanho.setText("Tamanho de N: ");

        inputTamanho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputTamanho.setText("8");
        inputTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTamanhoActionPerformed(evt);
            }
        });

        labelRepeticoes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelRepeticoes.setText("Quantidade de Repetições");

        inputRepeticoes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputRepeticoes.setText("1");
        inputRepeticoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRepeticoesActionPerformed(evt);
            }
        });

        outputRotinas.setColumns(20);
        outputRotinas.setRows(5);
        jScrollPane2.setViewportView(outputRotinas);

        labelRotina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRotina.setText("Rotina de Testes");

        botaoIniciarRotina.setText("Iniciar Rotina");
        botaoIniciarRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarRotinaActionPerformed(evt);
            }
        });

        botaoIncluirTeste.setText("Incluir Teste");
        botaoIncluirTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirTesteActionPerformed(evt);
            }
        });

        botaoLimparRotina.setText("Limpar Rotina");
        botaoLimparRotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparRotinaActionPerformed(evt);
            }
        });

        botaoLimparDados.setText("Limpar Dados do Documento");
        botaoLimparDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparDadosActionPerformed(evt);
            }
        });

        labelMensagem.setForeground(new java.awt.Color(204, 0, 51));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botaoNumLog.setText("Gerar Numeros Distribuição LogNormal");
        botaoNumLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNumLogActionPerformed(evt);
            }
        });

        labelMedia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelMedia.setText("Média");

        inputMedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputMedia.setText("0");
        inputMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMediaActionPerformed(evt);
            }
        });

        inputDesvio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputDesvio.setText("0");
        inputDesvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDesvioActionPerformed(evt);
            }
        });

        labelDesvio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelDesvio.setText("Desvio");

        labelDistRepeticoes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelDistRepeticoes.setText("Repetições");

        inputDistRepeticoes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputDistRepeticoes.setText("1000");
        inputDistRepeticoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDistRepeticoesActionPerformed(evt);
            }
        });

        labelExtra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelExtra.setText("Extra");

        inputExtra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputExtra.setText("0");
        inputExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputExtraActionPerformed(evt);
            }
        });

        botaoNumExp.setText("Gerar Numeros Distribuição Exponencial");
        botaoNumExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNumExpActionPerformed(evt);
            }
        });

        labelExtraExp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelExtraExp.setText("Extra");

        inputExtraExp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputExtraExp.setText("0");
        inputExtraExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputExtraExpActionPerformed(evt);
            }
        });

        inputLambda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputLambda.setText("0");
        inputLambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLambdaActionPerformed(evt);
            }
        });

        labelLambda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelLambda.setText("Lambda");

        labelDistRepeExp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelDistRepeExp.setText("Repetições");

        inputDistRepExp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputDistRepExp.setText("1000");
        inputDistRepExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDistRepExpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botaoIncluirTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botaoIniciarRotina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelTamanho)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelRotina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelRepeticoes)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(botaoLimparRotina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoLimparDados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoNumLog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelLambda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputLambda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelExtraExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputExtraExp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(labelDistRepeExp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputDistRepExp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoNumExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDesvio)
                                    .addComponent(labelMedia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputMedia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputDesvio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDistRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelExtra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputExtra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputDistRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMedia)
                            .addComponent(inputMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDistRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDistRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputDesvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDesvio)
                            .addComponent(labelExtra)
                            .addComponent(inputExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botaoNumLog, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLambda)
                            .addComponent(inputLambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDistRepeExp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDistRepExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputExtraExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelExtraExp)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelRotina)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTamanho)
                            .addComponent(inputTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRepeticoes)
                            .addComponent(inputRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoIniciarRotina)
                            .addComponent(botaoIncluirTeste))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoLimparRotina))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoRetornar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoNumExp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoLimparDados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRetornarActionPerformed
        this.controller.finalizarTestes();
    }//GEN-LAST:event_botaoRetornarActionPerformed

    private void inputRepeticoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRepeticoesActionPerformed
        this.botaoIncluirTeste.doClick();
    }//GEN-LAST:event_inputRepeticoesActionPerformed

    private void botaoLimparDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparDadosActionPerformed
        this.controller.iniciarLimpezaTestes();
    }//GEN-LAST:event_botaoLimparDadosActionPerformed

    private void botaoLimparRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparRotinaActionPerformed
        this.controller.limparRotina();
    }//GEN-LAST:event_botaoLimparRotinaActionPerformed

    private void botaoIniciarRotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarRotinaActionPerformed
        this.controller.iniciarRotina();
    }//GEN-LAST:event_botaoIniciarRotinaActionPerformed

    private void botaoIncluirTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirTesteActionPerformed
        this.controller.inserirTeste();
    }//GEN-LAST:event_botaoIncluirTesteActionPerformed

    private void inputTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTamanhoActionPerformed
        this.botaoIncluirTeste.doClick();
    }//GEN-LAST:event_inputTamanhoActionPerformed

    private void botaoNumLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNumLogActionPerformed
        this.controller.gerarNumerosDistribuicaoLog();
    }//GEN-LAST:event_botaoNumLogActionPerformed

    private void inputMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMediaActionPerformed

    private void inputDesvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDesvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDesvioActionPerformed

    private void inputDistRepeticoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDistRepeticoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDistRepeticoesActionPerformed

    private void inputExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputExtraActionPerformed

    private void botaoNumExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNumExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoNumExpActionPerformed

    private void inputExtraExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputExtraExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputExtraExpActionPerformed

    private void inputLambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLambdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLambdaActionPerformed

    private void inputDistRepExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDistRepExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDistRepExpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIncluirTeste;
    private javax.swing.JButton botaoIniciarRotina;
    private javax.swing.JButton botaoLimparDados;
    private javax.swing.JButton botaoLimparRotina;
    private javax.swing.JButton botaoNumExp;
    private javax.swing.JButton botaoNumLog;
    private javax.swing.JButton botaoRetornar;
    private javax.swing.JTextField inputDesvio;
    private javax.swing.JTextField inputDistRepExp;
    private javax.swing.JTextField inputDistRepeticoes;
    private javax.swing.JTextField inputExtra;
    private javax.swing.JTextField inputExtraExp;
    private javax.swing.JTextField inputLambda;
    private javax.swing.JTextField inputMedia;
    private javax.swing.JTextField inputRepeticoes;
    private javax.swing.JTextField inputTamanho;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDesvio;
    private javax.swing.JLabel labelDistRepeExp;
    private javax.swing.JLabel labelDistRepeticoes;
    private javax.swing.JLabel labelExtra;
    private javax.swing.JLabel labelExtraExp;
    private javax.swing.JLabel labelLambda;
    private javax.swing.JLabel labelMedia;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelRepeticoes;
    private javax.swing.JLabel labelRotina;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JTextArea outputRotinas;
    // End of variables declaration//GEN-END:variables

    public JTextArea getOutputRotinas() {
        return outputRotinas;
    }

    public JTextField getInputTamanho() {
        return inputTamanho;
    }

    public JTextField getInputRepeticoes() {
        return inputRepeticoes;
    }

    public JLabel getLabelMensagem() {
        return labelMensagem;
    }

    public JTextField getInputDesvio() {
        return inputDesvio;
    }

    public JTextField getInputMedia() {
        return inputMedia;
    }

    public JTextField getInputDistRepeticoes() {
        return inputDistRepeticoes;
    }

    public JTextField getInputExtra() {
        return inputExtra;
    }

    public JTextField getInputDistRepExp() {
        return inputDistRepExp;
    }

    public JTextField getInputLambda() {
        return inputLambda;
    }

    public JTextField getInputExtraExp() {
        return inputExtraExp;
    }
    
    
}
